name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        
      - name: Debug Folder Structure
        run: ls -R 

      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'  # Use a stable Node.js version

      - name: Install Dependencies
        run: npm install
        working-directory: ./back-end

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ag-grid-backend
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
          package: ./back-end